# ...
default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: mumbere
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: hello_rails_back_end_development
  # username: postgres  # Comment out or remove this line
  # password: mumbere  # Comment out or remove this line

# ...

production:
  <<: *default
  database: hello_rails_back_end_production
  username: hello_rails_back_end
  password: mumbere
